name: Bug Report
description: Report a bug in the image-annotate library
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - karlorz
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import component '...'
        2. Use with props '...'
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Library Version
      description: What version of @karlorz/image-annotate are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      description: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other

  - type: input
    id: react-version
    attributes:
      label: React Version
      description: What version of React are you using?
      placeholder: "19.1.0"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs
      description: Please copy and paste any relevant console output.
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, code samples, etc.)