name: Feature Request
description: Suggest a new feature for the image-annotate library
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees:
  - karlorz
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the information below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem you're trying to solve or the use case for this feature.
      placeholder: I'm trying to... but currently...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or how you envision this feature working.
      placeholder: It would be great if the library could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've tried... but...

  - type: dropdown
    id: component-type
    attributes:
      label: Component Type
      description: What type of component would this feature be for?
      options:
        - ImageCanvas
        - BoundingBoxTool
        - PolygonTool
        - PointTool
        - SelectionTool
        - ZoomPanControls
        - AnnotationList
        - LabelSelector
        - ExportPanel
        - ImageAnnotator (Main)
        - Other (New Component)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking my project)
        - High (Would significantly improve my workflow)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to help implement this feature
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here.